# Generated by Django 6.1.1 on 2026-09-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='prints/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(max_length=63, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('base_product', models.ForeignKey(blank=True, help_text="If set, this product is created by converting units of base_product (e.g. a printed hoodie's base_product is the blank hoodie). base_product itself must not have a base_product — conversions are one level deep, one-way.", limit_choices_to={'base_product__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_products', to='products.product')),
                ('print', models.ForeignKey(blank=True, help_text='If set, this product is a printed variant. Leave blank for raw/blank stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.print')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('CREATED', 'Created'), ('RECEIVED', 'Received'), ('PRINTED', 'Printed'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
