# Generated by Django 6.1.1 on 2026-10-06 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=63, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CLOTHING', 'Clothing'), ('ACCESSORY', 'Accessory'), ('BOOK', 'Book'), ('PRINT', 'Print'), ('PATCH', 'Patch')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('color', models.CharField(blank=True, max_length=63)),
                ('size', models.CharField(blank=True, max_length=63)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintPatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='print_patches/')),
                ('file_type', models.CharField(max_length=63)),
                ('print_patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.printpatch')),
            ],
        ),
        migrations.AddField(
            model_name='printpatch',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_patch', to='products.product'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('authors', models.JSONField(default=list)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('USED', 'Used')], max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='products.product')),
            ],
        ),
    ]
