# Generated by Django 5.2.17 on 2026-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('PICKING', 'Picking'), ('PROCESSING', 'Processing')], default='PICKING', max_length=20)),
            ],
        ),
    ]
