# Generated by Django 5.2.17 on 2026-09-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('IDLE', 'idle'), ('PICKING', 'Picking'), ('PROCESSING', 'Processing')], default='IDLE', max_length=20),
        ),
    ]
