# Generated by Django 5.2.17 on 2026-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0002_alter_crate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='status',
            field=models.CharField(choices=[('IDLE', 'idle'), ('PICKING', 'Picking'), ('PRINTING', 'Printing')], default='IDLE', max_length=20),
        ),
    ]
