# Generated by Django 6.1.1 on 2026-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
